
export const RULE_ADD_REQUEST = 'RULE_ADD_REQUEST'
export const RULE_ADD_SUCCESS = 'RULE_ADD_SUCCESS'
export const RULE_ADD_FAIL = 'RULE_ADD_FAIL'

export const RULE_DETAILS_REQUEST = 'RULE_DETAILS_REQUEST'
export const RULE_DETAILS_SUCCESS = 'RULE_DETAILS_SUCCESS'
export const RULE_DETAILS_FAIL = 'RULE_DETAILS_FAIL'


export const RULE_UPDATE_REQUEST = 'RULE_UPDATE_REQUEST'
export const RULE_UPDATE_SUCCESS = 'RULE_UPDATE_SUCCESS'
export const RULE_UPDATE_FAIL = 'RULE_UPDATE_FAIL'


export const RULE_LIST_REQUEST = 'RULE_LIST_REQUEST'
export const RULE_LIST_SUCCESS = 'RULE_LIST_SUCCESS'
export const RULE_LIST_FAIL = 'RULE_LIST_FAIL'

